logging:
  level:
    root: error
    com.jiu: info

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      max-active: 30
      min-idle: 1
      # 获取数据库连接等待的超时时间
      max-wait: 30000
      max-open-prepared-statements: -1
      # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      # 配置连接在池中的最大生存时间
      max-evictable-idle-time-millis: 400000
      # 系统启动时通过该sql语句验证数据库是否可用，如果不配置validationQuery，则下面三项无效
      validation-query: SELECT 1
      # 启用空闲连接检测，以便回收
      test-while-idle: true
      # 从连接池获取连接时，是否检测连接可用性，开启性能会有些许影响
      test-on-borrow: true
      # 释放连接到连接池时，是否检测连接可用性，开启性能会有些许影响
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mysql:
  datasource:
    url: jdbc:mysql://106.13.98.6:3306/running?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1qaz2wsx
    driverClassName: com.mysql.jdbc.Driver
oracle:
  datasource:
    #url: jdbc:oracle:thin:@127.0.0.1:1521/kefudb
    #username: root
    #password: root
    #driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:mysql://116.196.125.139:3306/running?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1qaz2wsx
    driverClassName: com.mysql.jdbc.Driver

#业务配置
business:
  systemStartTime: 2020-01-01