server:
  port: 9002
  servlet:
    context-path: /subpackage-demo
  session-timeout: 1800

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  devtools:
    restart:
      enabled: true
